#!/usr/bin/env bash
# Summary: Uninstall a version of Go.
#
# Usage: goenv uninstall <version>
#
# Versions should be in the form of N.N.N

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$GOENV_DEBUG" ] && {
  set -x
}

# Pull the desired version out of ARGV
version="$1"
version_dir="$GOENV_ROOT/versions/$version"

if [ -d "$version_dir" ]; then
  rm -rf "$version_dir"
  echo "Uninstalled $version"
else
  echo "goenv: version \`$version' isn't installed" >&2
  exit 1
fi
