#!/usr/bin/env bash
#
# Summary: Persist the preferred Go version in the cwd.
#
# Usage: goenv local <version>
#        goenv local --unset|-u

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$GOENV_DEBUG" ] && {
  set -x
}

# Set the version
version="$1"

case "$version" in
  "")
    echo "goenv: a version or --unset is required" >&2
    exit 1
    ;;

  "-u" | "--unset")
    if [ -f "$(pwd)/.go-version" ]; then
      rm "$(pwd)/.go-version"
      echo "Unset local .go-version file"
    else
      echo "goenv: no local version to unset" >&2
      exit 1
    fi
    ;;

  *)
    echo "$version" > "$(pwd)/.go-version"
    echo "Created $(pwd)/.go-version with $version"
    ;;
esac
